# Changes here will be overwritten by Copier
_commit: '4089880'
_src_path: gh:markm-io/pypackage-template
add_me_as_contributor: true
copyright_year: '2025'
documentation: true
email: mark@securehst.com
full_name: Mark Moreno
github_username: markm-io
has_cli: false
initial_commit: true
is_django_package: false
open_source_license: MIT
package_name: dataslicer
project_name: DataSlicer
project_short_description: DataSlicer is a powerful and lightweight Python tool designed
    to efficiently split large CSV and Excel (XLSX) files into smaller, more manageable
    chunks.
project_slug: dataslicer
run_uv_sync: true
setup_github: false
setup_pre_commit: true

